ERROR 2016-01-04 01:29:02,105 base 6468 16080 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:29:02,414 base 6468 15452 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:29:23,796 base 6468 13072 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:29:24,114 base 6468 8420 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:30:05,700 base 6468 8500 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:30:05,865 base 6468 15388 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:30:34,773 base 6468 2736 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:30:47,713 base 6468 3900 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:30:47,891 base 6468 14516 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:31:53,404 base 6468 4116 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:31:53,582 base 6468 15528 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:32:04,144 base 6468 8680 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:32:04,270 base 6468 15836 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:32:07,111 base 6468 14452 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:32:07,525 base 6468 11884 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:33:39,553 base 6468 10336 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:34:10,246 base 6468 15188 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 01:34:10,348 base 6468 11352 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 141, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 03:27:45,577 base 3525 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 274, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 03:28:40,042 base 3733 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 274, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 03:28:54,255 base 3735 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 275, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 03:29:54,252 base 3737 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 274, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 03:30:17,775 base 3737 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 274, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 03:31:03,163 base 3737 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 274, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 03:32:41,278 base 3781 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 275, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 03:32:53,043 base 3783 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 275, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 03:34:08,959 base 3785 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 274, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 03:35:01,814 base 3785 123145310715904 Internal Server Error: /askbar/submitQuestion
Traceback (most recent call last):
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/Users/ivan_l/GitLab/iSHU/pserver/iSHU/askbar/views.py", line 274, in submit_question
    guid = request.POST['guid']
  File "/Users/ivan_l/GitLab/shu_ask/fake/fake_server/venv/lib/python2.7/site-packages/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
ERROR 2016-01-04 14:05:22,621 base 1532 12508 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 140, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 14:22:48,029 base 1532 11252 Internal Server Error: /askbar/getAskList
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 140, in get_ask_list
    msg_res['Data'] = dict(enumerate(msg_res['Data']))
UnboundLocalError: local variable 'msg_res' referenced before assignment
ERROR 2016-01-04 14:37:15,584 base 1532 14412 Internal Server Error: /askbar/getQuestionDetailById
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 250, in get_question_detail_by_id
    msg_res = requests.get("http://api.shu.edu.cn/Mobile/Lehu/Question", data=data).json()
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\requests\models.py", line 805, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python27\Lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\Lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\Lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ERROR 2016-01-04 14:43:52,670 base 1532 14048 Internal Server Error: /askbar/submitAnswer
Traceback (most recent call last):
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\views\decorators\http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "D:\Desktop\iSHU\pserver\iSHU\askbar\views.py", line 264, in submit_answer
    'guid': request.POST['guid'],
  File "D:\Desktop\iSHU\pserver\venv\lib\site-packages\django\utils\datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'guid'"
